version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: teezinator/Dockerfile
    ports:
      - 8080:8080
    networks:
      - my-network
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    build: 
      context: .
      dockerfile: teezinator-db/Dockerfile
    ports:
      - 27022:27017
    networks:
      my-network:
        aliases:
          - mongodb

networks:
  my-network:
